import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
let source = fs.readFileSync('src/core/services/messageNotifications.ts', 'utf8').replace(/^import .*;\n/gm, '');
source = 'const invoke = async()=>{}; const WHATSAPP_API_URL=""; const runGoogleApiClient=async()=>({}); const useSettingsStore={getState:()=>({})};\n' + source;
const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { alertPrompt, notificationAnswer, messageNotifications } = await import('data:text/javascript;base64,' + Buffer.from(js).toString('base64'));
const single = {service:'whatsapp',messages:[{id:'1',sender:'Giri',body:'Hello'}],createdAt:Date.now()};
const batch = {...single,messages:Array.from({length:4},(_,i)=>({...single.messages[0],id:String(i)}))};
const mail = {...single,service:'gmail',messages:[{id:'m',sender:'Mayank Jha <m@example.com>'}]};
assert.match(alertPrompt(single),/Giri.*read it/);
assert.match(alertPrompt(batch),/4 new messages.*open WhatsApp/);
assert.match(alertPrompt(mail),/new email from Mayank Jha\./);
assert.equal(notificationAnswer('yes',single),'read');
assert.equal(notificationAnswer('yes',batch),'open');
assert.equal(notificationAnswer('yes',mail),'read');
assert.equal(notificationAnswer('no, can you read it for me?',batch),'read');
assert.equal(notificationAnswer('no',batch),'dismiss');
assert.equal(notificationAnswer('send it to Giri',single),null);
messageNotifications.pending=single;
assert.match(await messageNotifications.respond('no'),/Okay/);
assert.equal(await messageNotifications.respond('read it for me'),'Message from Giri: Hello');
messageNotifications.enqueue('whatsapp',single.messages);
messageNotifications.enqueue('whatsapp',single.messages);
assert.equal(messageNotifications.queue.length,1);
assert.equal(messageNotifications.queue[0].messages.length,1);
console.log('Message notification prompts, follow-ups and deduplication passed.');
