import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const transpile = source => ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const load = source => import('data:text/javascript;base64,'+Buffer.from(transpile(source)).toString('base64'));
const parser = await load(fs.readFileSync('src/features/spirits/voiceControl.ts','utf8'));
for (const text of ['add Mayank spirit','show spirit Mayank','please bring back Mayank spirit','can you add PIHU spirit?']) assert.equal(parser.parseSpiritCommand(text).action,'show');
assert.deepEqual(parser.parseSpiritCommand('hide Mayank spirit'),{action:'hide',name:'mayank'});
assert.deepEqual(parser.parseSpiritCommand('remove Mayank spirit from desktop'),{action:'remove',name:'mayank'});
assert.equal(parser.parseSpiritCommand('open spirit settings').action,'settings');
assert.equal(parser.parseSpiritCommand('hide all spirits').name,'all');
assert.equal(parser.parseSpiritCommand('send a message to Mayank'),null);
const state={enabled:true,activeIds:[],customSpirits:[],size:128,add(id){this.activeIds=[...new Set([...this.activeIds,id])]},remove(id){this.activeIds=this.activeIds.filter(x=>x!==id)},setEnabled(v){this.enabled=v},setSize(v){this.size=v}};
globalThis.spiritMock={state,category:'',widgets:{},toggleWidget(id){this.widgets[id]={isOpen:true}}};
const header=`const {state}=globalThis.spiritMock; const bundledSpirits=[{id:'mayank',name:'Mayank'},{id:'pihu',name:'PIHU'}]; const useSpiritsStore={getState:()=>state};const useSettingsStore={getState:()=>({setActiveSidebarCategory(v){globalThis.spiritMock.category=v}})};const useLayoutStore={getState:()=>globalThis.spiritMock};const resolveSpirit=${parser.resolveSpirit.toString()};\n`;
const source=fs.readFileSync('src/core/voice/intent/tools/spiritTools.ts','utf8').replace(/^import .*;\n/gm,'');
const {controlSpirit}=await load(header+source);
assert.equal(controlSpirit({action:'show',name:'Mayank'}).success,true);
controlSpirit({action:'show',name:'Mayank'});assert.deepEqual(state.activeIds,['mayank']);
controlSpirit({action:'hide',name:'Mayank'});assert.deepEqual(state.activeIds,[]);
controlSpirit({action:'show',name:'PIHU'});controlSpirit({action:'hide',name:'all'});assert.equal(state.enabled,false);assert.deepEqual(state.activeIds,['pihu']);
controlSpirit({action:'show',name:'PIHU'});assert.equal(state.enabled,true);
const before=[...state.activeIds];assert.equal(controlSpirit({action:'remove',name:'unknown'}).success,false);assert.deepEqual(state.activeIds,before);
assert.equal(controlSpirit({action:'size',size:999}).success,false);assert.equal(state.size,128);
controlSpirit({action:'settings'});assert.equal(globalThis.spiritMock.category,'spirits');assert.equal(globalThis.spiritMock.widgets['settings-window'].isOpen,true);
console.log('Spirit voice parsing and desktop controls passed.');
