import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import ts from 'typescript';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'pihu-spotify-test-'));
process.env.SPOTIFY_CONFIG_PATH=path.join(directory,'config.json');
const {startAuth,loadConfig,saveConfig,dispatch,CONFIG_PATH}=await import('../bin/spotify-runtime/bridge.mjs');
try {
 assert.equal((await dispatch({action:'status'})).connected,false);
 await assert.rejects(dispatch({action:'call',name:'getNowPlaying'}),/Connect Spotify/);
 await assert.rejects(startAuth({clientId:'test',clientSecret:'secret',redirectUri:'http://localhost:8888/callback'}),/redirect URI/);
 const probe=net.createServer();await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
 let authorizationUrl;let exchanges=0;
 const config={clientId:'test',clientSecret:'secret',redirectUri:`http://127.0.0.1:${port}/callback`};
 await startAuth(config,{openBrowser:async url=>{authorizationUrl=new URL(url)},fetchToken:async(url,options)=>{exchanges++;assert.equal(options.body.get('grant_type'),'authorization_code');return {ok:true,json:async()=>({access_token:'fixture-access',refresh_token:'fixture-refresh',expires_in:3600})}}});
 let res=await fetch(config.redirectUri+'?state=wrong&code=test');assert.equal(res.status,400);assert.equal(exchanges,0);assert.equal(fs.existsSync(CONFIG_PATH),false);
 res=await fetch(config.redirectUri+'?state='+authorizationUrl.searchParams.get('state')+'&code=test');assert.equal(res.status,200);assert.match(await res.text(),/Spotify is connected/);assert.equal(exchanges,1);
 assert.equal(fs.statSync(CONFIG_PATH).mode&0o777,0o600);
 const status=await dispatch({action:'status'});assert.equal(status.connected,true);assert.equal('clientSecret' in status,false);assert.equal('accessToken' in status,false);
 await dispatch({action:'disconnect'});assert.equal(loadConfig().accessToken,undefined);assert.equal(loadConfig().refreshToken,undefined);
 const occupied=net.createServer();await new Promise(resolve=>occupied.listen(0,'127.0.0.1',resolve));
 await assert.rejects(startAuth({...config,redirectUri:`http://127.0.0.1:${occupied.address().port}/callback`},{openBrowser:async()=>{throw Error('Browser must not open on occupied port')}}),/in use/);
 await new Promise(resolve=>occupied.close(resolve));
 await startAuth(config,{openBrowser:async url=>{authorizationUrl=new URL(url)},fetchToken:async()=>{throw Error('Denied login must not exchange a code')}});
 res=await fetch(config.redirectUri+'?state='+authorizationUrl.searchParams.get('state')+'&error=access_denied');assert.equal(res.status,400);await res.text();
 assert.equal((await dispatch({action:'status'})).connected,false);
 assert.match((await dispatch({action:'status'})).error,/declined/);
 const tools=await dispatch({action:'tools'});assert.equal(tools.length,30);assert(tools.some(t=>t.name==='getAvailableDevices'));
 await dispatch({action:'shutdown'});
 const source=fs.readFileSync('src/core/services/spotifyIntent.ts','utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
 const {parseSpotifyIntent}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
 assert.deepEqual(parseSpotifyIntent('play Perfect by Ed Sheeran on Spotify'),{query:'Perfect by Ed Sheeran',play:true});
 assert.equal(parseSpotifyIntent('pause Spotify').name,'pausePlayback');assert.equal(parseSpotifyIntent('set Spotify volume to 50').args.volumePercent,50);
 assert.equal(parseSpotifyIntent('set volume to 50 on Spotify').args.volumePercent,50);
 assert.equal(parseSpotifyIntent('play a video on YouTube'),null);
 console.log('Spotify OAuth state validation, token storage, disconnect, 30 MCP tools and voice parsing passed.');
} finally {await dispatch({action:'shutdown'});fs.rmSync(directory,{recursive:true,force:true});}
